# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160404_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='question',
            name='published_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
